### ISSUE TITLE
request: move from Github

### ISSUE THREAD

**Issue by ciami7** [arp242/uni#15]

**Comment by arp242** [comment]
Not entirely sure what to make of this issue, but not really interested at this point; sorry. You can still use the standard `git` tools and/or contact me by email if you don't want to use GitHub.

**Comment by ciami7** [comment]
github is proprietary software. there is better free software is available14.06.2020, 09:55, "Martin Tournoij" <notifications@github.com>:
Not entirely sure what to make of this issue, but not really interested at this point; sorry. You can still use the standard git tools and/or contact me by email if you don't want to use GitHub.

**Comment by arp242** [comment]
I have no problems with that.

**Comment by ciami7** [comment]
why, that is a totally stupid decision. you write free software then publish it to a proprietary software system. how can you do this? I don't understand it.14.06.2020, 09:59, "Martin Tournoij" <notifications@github.com>:
I have no problems with that.

**Comment by ciami7** [comment]
@arp242 reply

**Comment by arp242** [comment]
I don't write "Free Software"; I have many reservations about the entire concept.

I'm not sure why I need to justify myself to some random GitHub commenter about my choice of tooling. This is a little program I wrote over the course of almost 2 years 100% for my own reasons. I eventually released it because ... well, why not? Somewhat to my own surprise quite a few people seem to like it (great!), but releasing it isn't some sort of political action.

If you don't like GitHub or that this is hosted there: that's fine. Then don't use it. Problem solved. Please don't expect everyone to adhere to your own views and badger them when they don't. This is quite rude, and you're also being the worst advocate for Free Software.

**Comment by ciami7** [comment]
I am not a free software advocate. i am just a teenager interested is programming.In my experience Github is a stupidly  designed software. Also being proprietary. I like this program that you wrote and use it. What if you released your softwarewithout the src code. how many people will then get interested. Most of the current Open source community is using Github for which i feelvery bad. Most people seems don't care.

**Comment by arp242** [comment]
I see you've opened a bunch of similar issues in other repos. I can pretty much guarantee you that no-one will receive it as a welcome contribution. I assume you're well-intentioned, but people who release software on GitHub are usually familiar with the various alternatives and the pros and cons of them. So if they're on GitHub already then it's very very unlikely that an issue like this will make them move away from it. It will almost always be seen as disruptive, rather than helpful.

**Comment by ubidefeo** [comment]
@arp242 
we marked @ciami7 's issue on our repo as __invalid__ .
Do not engage, he's just a teenager who joined GH 48h ago and feels like he knows better.
Let life teach him a lesson :D

**Comment by arp242** [comment]
Dank je @ubidefeo I figured a little, eh, gentle instructions couldn't hurt. And it's not like I got much else to do today haha

**Comment by ciami7** [comment]
I am 19 years old. I had several of github account before. all of them are now deleted.Current software quality sucks. People make shit website but earn a lot of money while i am jobless.no one teach me to write kernel, os, compiler, graphics system. All they know how to use Linux.IMO Linux is piece of shit. it's a monopoly."Technology doesn't improve automatically, it takes a lot of people working very hard to improve it" - Elon

**Comment by arp242** [comment]
> I had several of github account before. all of them are now deleted

This should have been an incentive to reconsider your behaviour @ciami7, not keep doing the same stuff.

**Comment by ubidefeo** [comment]
@arp242 a quote from Elon Musk won't help his cause, IMO ;)
