### ISSUE TITLE
wasm-exec niceness

### ISSUE THREAD

**Issue by gedw99** [arp242/uni#37]
Its nice how you overlaoded the wasm exec js.

there is work to make it easier here: https://github.com/codefromthecrypt/wasmexec

Not saying its needed, but this provides a wasm and non wams execution agnostic approach

**Comment by gedw99** [comment]
oops i sent the fork, which is being integrated into wazero.

here is the correct link:  https://github.com/prep/wasmexec

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/tree/main/examples/gojs and also https://wazero.io/languages/ may help

wazero just cut its first beta tag (v1.0.0-beta.1) and also opened a [gophers slack](https://gophers.slack.com/) `#wazero` channel for support, updates and conversation! Note: You may need an [invite](https://invite.slack.golangbridge.org/) to join gophers.

**Comment by arp242** [comment]
The WASM version is just something I added to play around a bit with WASM; as far as I know it works well enough, but almost no one actually uses it – which is fine, because it's just something I added to play around a bit. I don't really have any interest in working on it much. If it turns out that some future changes in Go will horribly break it I will probably end up just removing it.
