### ISSUE TITLE
Unicode 16 beta support?

### ISSUE THREAD

**Issue by clin1234** [arp242/uni#48]
Just wondering if there is a way to handle beta Unicode releases?

**Comment by arp242** [comment]
Everything is hardcoded in the binary, so you can't really select the Unicode version.

I just made a few small changes to make it easier to re-generate the data using the Unicode beta; run `./unidata/gen/gen.zsh cache` to re-generate the data, and then `go build` to build a new version.

There is no Unicode 16 version for the https://www.unicode.org/Public/emoji/latest/emoji-test.txt file as near as I can tell, so that's still using Unicode 15.1.

**Comment by arp242** [comment]
You'll need `zsh`, `gawk` (GNU awk), `curl`, and a Go installation (including `gofmt`) for that. Most of that should be on most Linux and BSD system already, and probably also on macOS(?) If not, should be easy enough to install. I don't really know much about Windows so don't know how to run it there.

But I don't think it's worth supporting anything more than that. If you really want Unicode 16 and have trouble then tell me your system and I'll upload a binary.
